# Generated by Django 5.1 on 2024-09-08 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalfoto', models.ImageField(upload_to='image')),
                ('text', models.TextField(verbose_name='текст')),
                ('answer', models.IntegerField(verbose_name='ответ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата отзыва')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-date'],
            },
        ),
    ]
