# Generated by Django 5.1 on 2024-09-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalfoto', models.ImageField(upload_to='image', verbose_name='фото')),
                ('text', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'наша работа',
                'verbose_name_plural': 'наши работы',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='originalfoto',
            field=models.ImageField(upload_to='image', verbose_name='своё фото'),
        ),
    ]
