# Generated by Django 5.1 on 2024-10-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
