# Generated by Django 5.1 on 2024-09-01 14:05

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='телефон')),
                ('frame', models.CharField(max_length=50, verbose_name='оправа')),
                ('lenses', models.CharField(max_length=50, verbose_name='линзы')),
                ('price_master', models.CharField(max_length=50, verbose_name='работа мастера')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='скидка')),
                ('total', models.FloatField(verbose_name='итого')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата приема заказа')),
                ('date_productione', models.DateField(verbose_name='дата изготовления заказа')),
                ('DDP', models.FloatField(verbose_name='DDP')),
                ('OD_SPH', models.FloatField(verbose_name='OD_SPH')),
                ('OD_CYL', models.FloatField(verbose_name='OD_CYL')),
                ('OD_AX', models.FloatField(verbose_name='OD_AX')),
                ('OS_SPH', models.FloatField(verbose_name='OS_SPH')),
                ('OS_CYL', models.FloatField(verbose_name='OS_CYL')),
                ('OS_AX', models.FloatField(verbose_name='OS_AX')),
            ],
        ),
    ]
